config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             only: :omniauth_callbacks,
             controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  scope '(:locale)', locale: /en|vi/ do
    root 'static_pages#index'
    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'registrations' }
    as :user do
      get 'signup', to: 'devise/registrations#new'
      get 'signin', to: 'devise/sessions#new'
      post 'signin', to: 'devise/sessions#create'
      delete 'signout', to: 'devise/sessions#destroy'
    end
    resources :users, only: :index
    namespace :account do
      resource :address, only: %i[show create update]
      resource :paper, only: %i[show create update]
      resources :vehicles do
        delete '/destroy_image/:id', to: 'vehicles#destroy_image', as: 'destroy_image'
      end
      resources :orders, only: %i[index show edit update] do
        member do
          patch 'cancel'
        end
      end
      resources :rental_orders, only: %i[index show edit update] do 
        member do
          patch 'cancel'
          patch 'accept'
          patch 'processing'
          patch 'completed'
        end
      end
    end

    get '/admin', to: redirect('/admin/dashboard') #fix locale
    namespace :admin do
      get 'dashboard', to: 'admin#index'
      resources :users, only: %i[index show] do
        member do
          patch 'confirm_paper'
          patch 'reject_paper'
        end
      end
      resources :vehicle_options
      resources :orders, only: [:index]
      resources :partners, only: %i[index show] do
        member do
          get 'confirm'
          get 'cancel'
        end
      end
    end

    resource :search, only: [:show] do
      get 'vehicle/:id', to: 'searches#detail'
    end

    namespace :checkout do
      post 'confirm', action: :confirm
      get 'complete', action: :complete
      get 'confirmation', action: :confirmation
    end
    resources :orders, only: %i[create show edit update]
    resource :partner
    if Rails.env.production? || Rails.env.development?
      get '*path' => redirect('/404.html')
    end
  end
end

app/views/shared/_admin_header.slim
header.navbar.navbar-dark.sticky-top.bg-dark.flex-md-nowrap.p-0.shadow
  = link_to 'MOTOSHARE', root_path, class: "navbar-brand bg-secondary col-md-3 col-lg-2 me-0 px-3"
  .navbar-nav
    .nav-item.text-nowrap
      a class="nav-link px-3" Sign out

app/views/shared/_admin_navigation.slim
nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse"
  .position-sticky.pt-3
    ul.nav.flex-column
      li.nav-item
        = link_to admin_dashboard_path, class: "nav-link #{active_class("admin/admin")}" do
          = fa_icon "home", class: 'me-2'
          = t('.dashboard')
      li.nav-item
        = link_to admin_users_path, class: "nav-link #{active_class("admin/users")}" do
          = fa_icon "user", class: 'me-2'
          = t('.users')
      li.nav-item
        = link_to admin_orders_path, class: "nav-link #{active_class("admin/orders")}" do
          = fa_icon "cart-plus", class: 'me-2'
          = t('.orders')
      li.nav-item
        = link_to admin_partners_path, class: "nav-link #{active_class("admin/partners")}" do
          = fa_icon "clipboard", class: 'me-2'
          = t('.partners')
      li.nav-item
        a class="nav-link" data-bs-toggle="collapse" data-bs-target="#vehicle_option_collapse" aria-controls="vehicle_option_collapse"
          = fa_icon "car", class: 'me-2'
          = t ".vehicle"
        .collapse.show#vehicle_option_collapse
          ul.list-unstyled.fw-normal.small
            li
              = link_to t('.vehicle_option'), admin_vehicle_options_path, class: "ms-4 px-3 py-2 d-block text-decoration-none nav-link #{active_class("admin/vehicle_options")}"

app/views/shared/_loading.slim
div class="text-center"
  div class="spinner spinner-border text-primary loading-js" role="status"
    span class="visually-hidden" Loading...

app/views/shared/_sidebar.slim
.d-flex.align-items-center.mt-3
  = avatar_for(current_user.photo_url)
  span.fw-bold.ms-3 = current_user.full_name
.divider
.user-sidebar class="#{active_class('registrations')}"
  = fa_icon "user", class: 'user-sidebar__icon', style: 'width: 25px;color: #1F5CB8'
  = link_to t(".account"), edit_user_registration_path, class: 'user-sidebar__link'
.user-sidebar class="#{active_class('account/addresses')}"
  = fa_icon "location-arrow", class: 'user-sidebar__icon', style: 'width: 25px;color: #009F75'
  = link_to t(".address"), account_address_path, class: 'user-sidebar__link'
.user-sidebar class="#{active_class('account/papers')}"
  = fa_icon "address-card", class: 'user-sidebar__icon', style: 'width: 25px;color: #438eeb'
  = link_to t(".paper"), account_paper_path, class: 'user-sidebar__link'
.user-sidebar class="#{active_class('account/orders')}"
  = fa_icon "clipboard", class: 'user-sidebar__icon', style: 'width: 25px;color: #888'
  = link_to t(".order"), account_orders_path, class: 'user-sidebar__link'
- if current_user.is_partner
  .divider
  p.fw-bold = t('.partner')
  .user-sidebar class="#{active_class('account/rental_orders')}"
    = fa_icon "car", class: 'user-sidebar__icon', style: 'width: 25px;color: #ea7'
    = link_to t(".rental_order"), account_rental_orders_path, class: 'user-sidebar__link'
  .user-sidebar class="#{active_class('account/vehicles')}"
    = fa_icon "car", class: 'user-sidebar__icon', style: 'width: 25px;color: #ea7'
    = link_to t(".vehicles"), account_vehicles_path, class: 'user-sidebar__link'