config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             only: :omniauth_callbacks,
             controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  scope '(:locale)', locale: /en|vi/ do
    root 'static_pages#index'
    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'registrations' }
    as :user do
      get 'signup', to: 'devise/registrations#new'
      get 'signin', to: 'devise/sessions#new'
      post 'signin', to: 'devise/sessions#create'
      delete 'signout', to: 'devise/sessions#destroy'
    end
    resources :users, only: :index
    namespace :account do
      resource :address, only: %i[show create update]
      resource :paper, only: %i[show create update]
      resources :vehicles do
        delete '/destroy_image/:id', to: 'vehicles#destroy_image', as: 'destroy_image'
      end
      resources :orders, only: %i[index show edit update] do
        member do
          patch 'cancel'
        end
      end
      resources :rental_orders, only: %i[index show edit update] do 
        member do
          patch 'cancel'
          patch 'accept'
          patch 'processing'
          patch 'completed'
        end
      end
    end

    get '/admin', to: redirect('/admin/dashboard') #fix locale
    namespace :admin do
      get 'dashboard', to: 'admin#index'
      resources :users, only: %i[index show] do
        member do
          patch 'confirm_paper'
          patch 'reject_paper'
        end
      end
      resources :vehicle_options
      resources :orders, only: [:index]
      resources :partners, only: %i[index show] do
        member do
          get 'confirm'
          get 'cancel'
        end
      end
    end

    resource :search, only: [:show] do
      get 'vehicle/:id', to: 'searches#detail'
    end

    namespace :checkout do
      post 'confirm', action: :confirm
      get 'complete', action: :complete
      get 'confirmation', action: :confirmation
    end
    resources :orders, only: %i[create show edit update]
    resource :partner
    if Rails.env.production? || Rails.env.development?
      get '*path' => redirect('/404.html')
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  photo_url              :text
#  birth                  :datetime
#  phone                  :string
#  gender                 :integer
#  is_partner             :boolean          default(FALSE)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  provider               :string
#  uid                    :string
#  is_admin               :boolean
#
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :confirmable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :trackable,
         :lockable,
         :omniauthable,
         omniauth_providers: %i[facebook google_oauth2]
  mount_uploader :photo_url, PictureUploader
  before_save :downcase_email

  has_one :paper, dependent: :destroy
  has_one :address, dependent: :destroy
  has_one :partner_history, dependent: :destroy
  has_many :vehicles, dependent: :destroy
  has_many :orders, class_name: 'Order', foreign_key: 'renter_id'
  has_many :rental_orders, class_name: 'Order', foreign_key: 'owner_id'

  validate :avatar_size
  validates :email, presence: true
  validates :first_name, presence: true,
                         length: { minimum: 2 }
  validates :last_name, presence: true,
                        length: { minimum: 2 }
  enum gender: {
    other: 0,
    male: 1,
    female: 2
  }

  accepts_nested_attributes_for :paper

  def self.from_omniauth(auth)
    result = User.where(email: auth.info.email).first
    return result if result.present?

    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      # user.photo_url = auth.info.image
      user.skip_confirmation!
    end
  end

  def downcase_email
    self.email = email.downcase
  end

  def full_name
    "#{last_name} #{first_name}"
  end

  private

  def avatar_size
    return unless photo_url.size > 3.megabytes

    errors.add(:photo_url, I18n.t('image.min'))
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    def index
      @users = User.all

      respond_to do |format|
        format.html
        format.json { render json: @users.as_json }
      end
    end

    def reject_paper
      user = User.find_by(id: params[:id])
      return redirect_to request.referrer, alert: t('.user_not_found') unless user.present?

      return if user.paper.rejected?

      user.paper.status = :rejected
      if user.save
        redirect_to admin_user_path(user), notice: t('.reject_success')
      else
        redirect_to request.referrer, alert: t('.reject_failure')
      end
    end

    def confirm_paper
      user = User.find_by(id: params[:id])
      return redirect_to request.referrer, alert: t('.user_not_found') unless user.present?

      return if user.paper.confirmed?

      user.paper.status = :confirmed
      user.paper.verified_at = Time.current
      if user.save
        redirect_to admin_user_path(user), notice: t('.confirm_success')
      else
        redirect_to request.referrer, alert: t('.confirm_failure')
      end
    end

    def show
      @user = User.includes(:paper, :address, :vehicles).find_by(id: params[:id])

      respond_to do |format|
        format.html
        format.json { render json: @user, serializer: UserSerializer }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/helpers/admin/users_helper.rb
module Admin
  module UsersHelper
    def user_info_fields(user)
      user.attributes.slice('email', 'first_name', 'last_name', 'phone', 'birth',
                            'gender', 'is_partner', 'is_admin', 'created_at').compact
    end

    def user_paper_infos(paper)
      paper.slice('card_number', 'card_front_url', 'card_back_url',
                  'driver_number', 'driver_front_url').compact
    end
  end
end

app/views/admin/users/index.slim
= content_for :head do
  = javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload'
  script src="https://unpkg.com/bootstrap-table@1.21.0/dist/bootstrap-table-locale-all.min.js"
= content_for :page_header
  h2 = t ".users"
  nav
    ol.breadcrumb
      li.breadcrumb-item
        = link_to t('.home'), admin_dashboard_path
      li.breadcrumb-item.active = t ".users"
.row
  .col-md-12
    #toolbar
      button#remove.btn.btn-danger.ms-2 disabled=true
        = fa_icon 'trash'
    table#table data-locale="#{params[:locale]}"
      thead
        tr
          th data-field="state" data-checkbox="true"
          th data-field="last_name" data-sortable="true"
            = t '.last_name'
          th data-field="first_name" data-sortable="true"
            = t '.first_name'
          th data-field="email"
            = t '.email'
          th data-field="phone"
            = t '.phone'
          th data-field="gender"
            = t '.gender'
          th data-field="birth" data-formatter="dateFormat"
            = t '.birth'
          th data-field="is_partner"
            = t '.is_partner'
          th data-field="is_admin"
            = t '.is_admin'
          th data-field="id" data-formatter="actionFormatter"
            = t '.action'

javascript:
  function dateFormat(value) {
    if(!value) return;
    return moment(value).format('DD/MM/YYYY HH:mm')
  }

  function actionFormatter(value) {
    return `
      <a class='btn btn-link' href="users/${value}">
        #{t('.show')}
      </a>`
  }

app/views/admin/users/show.slim
= content_for :page_header
  h2 = t ".title"
  nav
    ol.breadcrumb
      li.breadcrumb-item
        = link_to t('.home'), admin_dashboard_path
      li.breadcrumb-item
        = link_to t('.users'), admin_users_path
      li.breadcrumb-item.active = t ".show"
.row.py-3
  .col-md-5
    .d-flex.justify-content-center.mb-3
      = avatar_for(@user.photo_url, 150)
    - user_info_fields(@user).each do |name, value|
      dl.row.mb-2
        dt.col-md-3
          = t(".#{name}")
        dd.col-md-9
          - case name
          - when 'birth'
            = l(value)
          - when 'gender'
            = t(".#{value}")
          - when 'is_partner', 'is_admin'
            .badge.bg-primary = value
          - when 'created_at'
            = distance_of_time_in_words_to_now(value)
          - else
            = value
    - if @user.address.present?
      dl.row.mb-2
        dt.col-md-3
          = t(".address")
        dd.col-md-9
          = @user.address.full_address
  .col-md-7
    .d-flex.align-items-center.mb-3
      h4.fw-bold 
        = t('.papers')
        span.badge.bg-primary.ms-3 = t(".#{@user.paper.status}") if @user.paper.present?
    .divider
    - if @user.paper.present?
      - user_paper_infos(@user.paper).each do |name, value|
        dl.row.mb-2
          dt.col-md-3
            = t(".#{name}")
          dd.col-md-9
            - case name
            - when 'card_front_url', 'card_back_url', 'driver_front_url'
              - if value.present?
                = cl_image_tag(value, width: 300, crop: :fill, class: 'border mb-3 d-block')
            - else
              = value
      .row
        .col-md-9.offset-md-3.d-flex.gap-2
          - unless @user.paper.confirmed?
            = link_to t('.confirm_paper'), confirm_paper_admin_user_path(@user),
              method: 'PATCH', class: 'btn btn-primary', data: {confirm: t('.dialog_confirm')}
            = link_to t('.reject_paper'), reject_paper_admin_user_path(@user),
              method: 'PATCH', class: 'btn btn-danger', data: {confirm: t('.dialog_reject')}
    - else
      .text-center = t('.empty_paper')